[testServer]
BROKER_HOST = 100.90.255.11
BROKER_PORT = 5672
USER = db
PASSWORD = db123
VHOST = githappensHost
EXCHANGE = githappensExchange
QUEUE = githappensQueue
;EXCHANGE_TYPE = topic
AUTO_DELETE = true

